minimumReleaseAgeExclude:
  - bumpp@12.0.0
  - fast-npm-meta@2.2.0
  - taze@19.15.0
packages: []
allowBuilds:
  esbuild: true
  simple-git-hooks: true
catalogs:
  build:
    tsdown: ^0.22.14
  dev:
    bumpp: ^12.1.1
    pncat: ^0.13.0
    simple-git-hooks: ^2.13.1
    taze: ^19.17.0
    tsx: ^4.23.5
    typescript: ^6.0.3
  inlined:
    p-retry: ^8.0.0
    validate-npm-package-name: ^8.0.0
  lint:
    '@octohash/eslint-config': ^0.5.3
    eslint: ^10.8.0
    lint-staged: ^17.3.0
  prod:
    empathic: ^2.0.1
    fast-npm-meta: ^2.2.0
    package-manager-detector: ^1.8.0
    smol-toml: ^1.7.1
    verkit: ^0.3.1
    yaml: ^2.9.0
  test:
    vitest: ^4.1.10
  types:
    '@types/node': ^26.1.2
    '@types/validate-npm-package-name': ^4.0.2
